
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-1', N'accident:Multi-car collision blocking left turn lane');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-2', N'construction:Sidewalk repair affecting pedestrian crossing timing');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-3', N'incident:Delivery truck double-parked - minor traffic backup');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-4', N'maintenance:Street cleaning operation - temporary lane restriction');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-5', N'construction:Lane closure for water main repair - expect delays');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-6', N'weather:Wind advisory affecting high-profile vehicles');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-7', N'incident:Traffic signal malfunction - manual control implemented');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-8', N'construction:Gas line maintenance - reduced lane capacity');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-9', N'weather:Heavy rain reducing visibility and slowing traffic');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-10', N'incident:Street vendor setup causing pedestrian overflow');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-11', N'maintenance:Pavement patching during off-peak hours');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-12', N'incident:Disabled vehicle in right lane - tow truck en route');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-13', N'construction:Sewer line replacement - single lane operation');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-14', N'weather:Morning fog reducing visibility conditions');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-15', N'incident:Minor fender bender - vehicles moving to shoulder');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-16', N'maintenance:Traffic signal upgrade - temporary timing changes');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-17', N'construction:Underground cable installation - lane shifts active');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-18', N'incident:Emergency vehicle response - temporary lane closure');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-19', N'weather:Ice warning - reduced speed advisory in effect');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-20', N'construction:Bridge inspection - intermittent traffic holds');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-21', N'construction:Utility work on Shore Boulevard - one lane closed');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-22', N'incident:Large vehicle breakdown - recovery operation underway');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-23', N'weather:Strong crosswinds affecting vehicle stability');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-24', N'maintenance:Intersection cleaning - brief signal timing adjustment');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-25', N'maintenance:Traffic light servicing during off-peak hours');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-26', N'construction:Roadway milling operation - noise and dust advisory');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-27', N'incident:Police investigation - temporary traffic redirection');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-28', N'weather:Sun glare advisory during evening commute hours');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-29', N'construction:Curb and gutter repair - parking restrictions active');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-30', N'accident:Fender bender cleared - residual congestion possible');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-31', N'maintenance:Street sign installation - brief lane occupation');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-32', N'incident:Oversize load transport - escort vehicle convoy');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-33', N'weather:Light snow accumulation - reduced traction conditions');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-34', N'construction:Sidewalk reconstruction - pedestrian detour in place');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-35', N'incident:Traffic signal stuck on red - technician dispatched');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-36', N'maintenance:Pothole repair crew - temporary lane restriction');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-37', N'weather:Fog advisory affecting Rockaway Beach area');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-38', N'construction:Storm drain maintenance - periodic lane closures');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-39', N'incident:Vehicle fire extinguished - debris cleanup in progress');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-40', N'weather:High tide flooding - water on roadway');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-41', N'construction:Electrical work - traffic signal timing modified');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-42', N'incident:Abandoned vehicle removal - tow operation scheduled');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-43', N'maintenance:Crosswalk painting - temporary pedestrian rerouting');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-44', N'weather:Flash flood warning - avoid low-lying areas');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-45', N'incident:Police activity - temporary traffic control in effect');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-46', N'construction:Tree removal operation - crane activity present');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-47', N'weather:Dense fog - reduced visibility below 100 feet');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-48', N'incident:Fuel spill cleanup - hazmat team on scene');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-49', N'construction:Race Track Road repaving - alternate route suggested');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-50', N'maintenance:Traffic counting equipment installation');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-51', N'incident:Animal on roadway - wildlife control contacted');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-52', N'weather:Black ice formation - extreme caution advised');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-53', N'construction:Manhole cover replacement - temporary traffic pattern');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-54', N'incident:Multi-vehicle accident - emergency responders on scene');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-55', N'weather:Thunderstorm warning - seek shelter if outdoors');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-56', N'maintenance:Street light bulb replacement - cherry picker present');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-57', N'construction:Driveway installation - intermittent lane blockage');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-58', N'incident:Medical emergency - ambulance blocking travel lane');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-59', N'weather:Hail damage assessment - debris on roadway');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-60', N'construction:Fire hydrant maintenance - water pressure testing');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-61', N'incident:Bicycle accident - first aid being administered');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-62', N'maintenance:Road salt application - slow-moving spreader truck');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-63', N'weather:Tornado watch issued - monitor weather conditions');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-64', N'construction:Drainage pipe installation - excavation in progress');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-65', N'construction:Road resurfacing on Culver Avenue - reduced capacity');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-66', N'incident:Power line down - utility crew establishing safety zone');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-67', N'weather:Hurricane evacuation route - increased traffic volume');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-68', N'maintenance:Guardrail inspection - work vehicle in shoulder');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-69', N'construction:Fiber optic cable burial - trenching operation active');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-70', N'incident:Chemical spill contained - decontamination in progress');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-71', N'weather:Severe thunderstorm - heavy rain and lightning');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-72', N'maintenance:Traffic camera adjustment - brief signal interruption');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-73', N'construction:Retaining wall repair - single lane alternating traffic');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-74', N'incident:Pedestrian accident - intersection temporarily closed');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-75', N'weather:Drought conditions - dust advisory for visibility');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-76', N'maintenance:Pavement marking renewal - lane position changes');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-77', N'maintenance:Signal timing optimization in progress');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-78', N'construction:Culvert replacement - temporary road closure');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-79', N'incident:Hazardous material transport - escort required');
INSERT INTO events (deviceId, eventString) VALUES (N'sensor-80', N'weather:Extreme heat advisory - pavement buckling possible');